# this is a multi language project see
# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      before_script:
        # prepare the java fat jar installation - so that it will not download anything anymore when the test script runs
        - cd java
        - mvn package -D skipTests -D createAssembly=true
        - cd ..
      addons:
        apt:
          packages:
            - openjdk-8-jdk

      script:
        # start the test script which will run the echoServer
        #- ./test -pa
        - ./test -p
#       - python -m unittest discover

    - language: java
      dist: xenial
      jdk: openjdk8
      before_script:
        - cd java
      script:
        - mvn clean install -D gpg.skip
