# this is a multi language project see
# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      before_script:
#       - cd python
      addons:
        apt:
          packages: openjdk-8-jdk

      script:
        - ./test -pa
#       - python -m unittest discover

    - language: java
      dist: xenial
      jdk: openjdk8
      before_script:
        - cd java
      script:
        - mvn clean install -D gpg.skip
