# use 16.04
dist: xenial
# this is a java project using maven
language: java
# we'll get java 11 or higher if we don't do this
jdk:
  - openjdk8
before_script:
  - cd java
# switch off gpg handling
script:
  - mvn clean install -Dgpg.skip=true
