#!/bin/bash
# WF 2020-01-02
# create a release see https://packaging.python.org/tutorials/packaging-projects/
python3 setup.py sdist bdist_wheel
python3 -m twine upload -u __token__ --repository-url https://test.pypi.org/legacy/ dist/*
